---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert git is installed
      ansible.builtin.assert:
        that:
          - "'git' in ansible_facts.packages"
        fail_msg: "git is not installed"
        success_msg: "git is installed"
